### PR TITLE
Refactor comm

### PR DESCRIPTION
**Pull request by netgusto**
Major refactor of Comm server.

* Uses UDP instead of TCP
* Complete separation of comm and Game server
* Abstracted agent, so that non-networked agents can be implemented if needed (like in-game creeps)
* Separation of Game server and state management (mutation methods like steer, shoot now belong to the server state, and their parameters are parsed only when the mutation method is fully known)

UDP seems to improve performance a lot; after investigation, I think the TCP bottleneck might be a bad implementation of TCP congestion handling on the docker network stack.

### CODE REVIEW

**Comment by xtuc** [comment]
J'ai toujours des problèmes de timeout. Le nombre de goroutine (en vol) n'est pas stable.

Je vais essayer de comprendre pourquoi

**Comment by edi9999** [comment]
I also see some very long ticks : 

Most of the time, it ticks in <5ms, but sometimes, it goes to 100ms

```
2017/04/07 09:26:57 # Nombre de goroutines en vol : 41
2017/04/07 09:26:57
2017/04/07 09:26:58 Tick ! <TickTurn(199)>
2017/04/07 09:26:58
2017/04/07 09:26:58 All agents ticked in 3.47 ms
2017/04/07 09:26:58 ProcessMutations() took 0.12 ms; next tick in 996.41 ms
2017/04/07 09:26:58
2017/04/07 09:26:58
2017/04/07 09:26:58 # Nombre de goroutines en vol : 39
2017/04/07 09:26:58
2017/04/07 09:26:59 Tick ! <TickTurn(200)>
2017/04/07 09:26:59
2017/04/07 09:26:59 All agents ticked in 3.37 ms
2017/04/07 09:26:59 ProcessMutations() took 0.06 ms; next tick in 996.57 ms
2017/04/07 09:26:59
2017/04/07 09:26:59
2017/04/07 09:26:59 # Nombre de goroutines en vol : 42
2017/04/07 09:26:59
2017/04/07 09:27:00 Tick ! <TickTurn(201)>
2017/04/07 09:27:00
2017/04/07 09:27:00 All agents ticked in 96.93 ms
2017/04/07 09:27:00 ProcessMutations() took 0.14 ms; next tick in 902.93 ms
2017/04/07 09:27:00
2017/04/07 09:27:00
```

**Comment by edi9999** [comment]
Even with AGENT=1 TPS=1 , the agent sometimes takes 100ms to tick ...

**Comment by edi9999** [comment]
After investigating a bit, I found that the 100ms are passed in : 

```
if utils.ChanTimeout(agent.GetTickedChan(), timeoutduration) {
```

**Comment by netgusto** [comment]
> if utils.ChanTimeout(agent.GetTickedChan(), timeoutduration) {

Makes sense; this is by design, as it waits until all agents have tocked, or the timeout (60% of the turn duration), whichever comes first.

This seems to mean then that the problem might be in the actual layer outside the server : network or agents.

**Pull request merged**
